from click import clear
t1 = (input("Digite a tarefa 01: "))
t2 = (input("Digite a tarefa 02: "))
t3 = (input("Digite a tarefa 03: "))
t4 = (input("Digite a tarefa 04: "))
t5 = (input("Digite a tarefa 05: "))
t6 = (input("Digite a tarefa 06: "))
t7 = (input("Digite a tarefa 07: "))
t8 = (input("Digite a tarefa 08: "))
t9 = (input("Digite a tarefa 09: "))
t10 = (input("Digite a tarefa 10: "))
clear()
print("tarefa 01 - ", t1)
print("tarefa 02 - ", t2)
print("tarefa 03 - ", t3)
print("tarefa 04 - ", t4)
print("tarefa 05 - ", t5)
print("tarefa 06 - ", t6)
print("tarefa 07 - ", t7)
print("tarefa 08 - ", t8)
print("tarefa 09 - ", t9)
print("tarefa 10 - ", t10)